[tool.poetry]
name = "gingerino"
version = "0.1.5"
description = "Parse strings using Jinja-style templates"
authors = ["Marco Burro <marcoburro98@gmail.com>"]

readme = "README.md"
repository = "https://github.com/buurro/gingerino"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
ruff = "^0.1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
