name: "Test"
on:
  pull_request:
  push:
    branches: ['main']
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run .#check
    - run: nix run .#test
